# -*- coding: utf-8 -*-
"""Alcance_Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v4gb-_zICelszRfZyZF0RkO9IH2oy03d

<h1 style="color:#267bbd"}><center><b>BARANGAY CENSUS</h1></center></b></style>
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats
sns.set(color_codes = True)

df = pd.read_csv('dasma_concensus.csv')
df

db = df[(df['Status']== 'Barangay')]
db

less_than_10000_df = db[(db['2000'] < 10000) &
                           (db['2010'] < 10000) &
                           (db['2015'] < 10000) &
                           (db['2020'] < 10000)]
less_than_10000_df

greater_than_10000_df = db[(db['2000'] >= 10000) &
                           (db['2010'] >= 10000) &
                           (db['2015'] >= 10000) &
                           (db['2020'] >= 10000)]
greater_than_10000_df

db = db.sample(30)
db

sns.set_theme(style="whitegrid", palette="pastel")

sns.set_palette('deep')

sns.scatterplot(x='Name', y='Cases', data=db, color = 'purple')
sns.scatterplot(x='Name', y='Recoveries', data=db, color='green')
sns.scatterplot(x='Name', y='Deaths', data=db, color='red')
plt.title('Scatter Plot Covid-19 Cases, Recoveries, and Deaths')
plt.xlabel('Barangay')
plt.ylabel('Population')
plt.xticks(db['Name'], rotation=90 , fontsize=5)

plt.legend(['Cases','Recoveries','Deaths'])

plt.show()

sns.set_theme(style="whitegrid", palette="pastel")

sns.set_palette('deep')

sns.lineplot(x='Name', y='Cases', data=db, color='purple',label='Cases')
sns.lineplot(x='Name', y='Recoveries', data=db,color='green', label='Recoveries')
sns.lineplot(x='Name', y='Deaths', data=db,color='red', label='Deaths')
plt.title('Line Graph Covid-19 Cases, Recoveries, and Deaths')
plt.xlabel('Barangay')
plt.ylabel('Population')


plt.xticks(db['Name'], rotation=90 , fontsize=6)

plt.legend()

plt.show()

sns.set_theme(style="whitegrid", palette="pastel")
sns.barplot(x='Name', y='Cases', data=db,color='purple',label='Cases')
sns.barplot(x='Name', y='Recoveries', data=db, color='green',label='Recoveries')
sns.barplot(x='Name', y='Deaths', data=db,color='red',label='Deaths')
plt.title('Bar Graph Covid-19 Cases, Recoveries, and Deaths')
plt.xlabel('Barangay')
plt.ylabel('Population')
plt.xticks(db['Name'], rotation=90 , fontsize=6)
plt.legend()
plt.show()

plt.figure(figsize=(8, 8))


wedges, texts, autotexts = plt.pie(db['Cases'], labels=db['Name'], autopct='%1.1f%%', startangle=140)


for text in texts:
    text.set_fontsize(10)


for autotext in autotexts:
    autotext.set_fontsize(3)


plt.title('COVID-19 Cases by Barangay')

plt.figure(figsize=(8, 6))

sns.set_theme(style="whitegrid", palette="pastel")

sns.histplot(x='Cases', data=db, kde=True, bins=20, multiple='stack',linewidth=.6, color="Purple")


plt.ylabel('Count')
plt.xlabel('Number of Cases')
plt.title('Frequency of COVID-19 Cases in Barangay')

plt.figure(figsize=(8, 6))

sns.set_theme(style="whitegrid", palette="pastel")

sns.histplot(x='Recoveries', data=db, kde=True, bins=20, multiple='stack',linewidth=.6, color="Green")


plt.ylabel('Count')
plt.xlabel('Number of Cases')
plt.title('Frequency of COVID-19 Recoveries in Barangay')

plt.figure(figsize=(8, 6))

sns.set_theme(style="whitegrid", palette="pastel")

sns.histplot(x='Deaths', data=db, kde=True, bins=20, multiple='stack',linewidth=.6, color="Red")


plt.ylabel('Count')
plt.xlabel('Number of Cases')
plt.title('Frequency of COVID-19 Deaths in Barangay')

dc = df[(df['Status']== 'City')]
dc

dc = dc.sample(11)
dc

sns.set_theme(style="whitegrid", palette="pastel")
sns.scatterplot(x='Name', y='Cases', data=dc,color='purple', label='Cases')
sns.scatterplot(x='Name', y='Recoveries', data=dc, color='green',label='Recoveries')
sns.scatterplot(x='Name', y='Deaths', data=dc, color='red',label='Deaths')
plt.title('Scatter Plot Covid-19 Cases, Recoveries, and Deaths')
plt.xlabel('Cities')
plt.ylabel('Population')
plt.xticks(dc['Name'], rotation=90 , fontsize=10)
plt.legend()
plt.show()

sns.set_theme(style="whitegrid", palette="pastel")
sns.lineplot(x='Name', y='Cases', data=dc,color='purple',label='Cases')
sns.lineplot(x='Name', y='Recoveries', data=dc,color='green',label='Recoveries')
sns.lineplot(x='Name', y='Deaths', data=dc,color='red',label='Deaths')
plt.title('Line Graph Covid-19 Cases, Recoveries, and Deaths')
plt.xlabel('Cities')
plt.ylabel('Population')
plt.xticks(dc['Name'], rotation=90 , fontsize=6)
plt.legend()
plt.show()

plt.figure(figsize=(8, 8))


wedges, texts, autotexts = plt.pie(dc['Cases'], labels=dc['Name'], autopct='%1.1f%%', startangle=140)


for text in texts:
    text.set_fontsize(10)


for autotext in autotexts:
    autotext.set_fontsize(5)


plt.title('COVID-19 Cases by Cities')

plt.figure(figsize=(8, 6))

sns.set_theme(style="whitegrid", palette="pastel")

sns.histplot(x='Cases', data=dc, kde=True, bins=20, multiple='stack',linewidth=.6, color="Purple")
#sns.histplot(x='Recoveries', data=dc, kde=True, bins=20, multiple='stack',linewidth=.6, color="Blue")
#sns.histplot(x='Deaths', data=dc, kde=True, bins=20, multiple='stack',linewidth=.6, color="Red")

plt.ylabel('Count')
plt.xlabel('Number of Cases')
plt.title('Frequency of COVID-19 Cases,Recoveries and Deaths in Cities')

plt.figure(figsize=(8, 6))

sns.set_theme(style="whitegrid", palette="pastel")

#sns.histplot(x='Cases', data=dc, kde=True, bins=20, multiple='stack',linewidth=.6, color="Purple")
sns.histplot(x='Recoveries', data=dc, kde=True, bins=20, multiple='stack',linewidth=.6, color="Blue")
#sns.histplot(x='Deaths', data=dc, kde=True, bins=20, multiple='stack',linewidth=.6, color="Red")

plt.ylabel('Count')
plt.xlabel('Number of Cases')
plt.title('Frequency of COVID-19 Cases,Recoveries and Deaths in Cities')

plt.figure(figsize=(8, 6))

sns.set_theme(style="whitegrid", palette="pastel")

#sns.histplot(x='Cases', data=dc, kde=True, bins=20, multiple='stack',linewidth=.6, color="Purple")
#sns.histplot(x='Recoveries', data=dc, kde=True, bins=20, multiple='stack',linewidth=.6, color="Blue")
sns.histplot(x='Deaths', data=dc, kde=True, bins=20, multiple='stack',linewidth=.6, color="Red")

plt.ylabel('Count')
plt.xlabel('Number of Cases')
plt.title('Frequency of COVID-19 Deaths in Cities')

